//! What a profile's options *are* — declared once, used three times.
//!
//! Before this module the same constraints existed twice: `validate_options` rejected
//! `quality: 200`, and the processors independently fell back to 90 when the key was
//! absent. Nothing tied the two together, and a client could only discover the accepted
//! values by sending a bad one and reading the `InvalidArgs` back — which is not
//! something a GUI can build a picker from.
//!
//! So the constraints move here, into one table per [`ProfileKind`], and everything else
//! is derived from it:
//!
//! - [`validate`] decides what `Profile1.Options` accepts,
//! - [`schema`] is what `Profile1.OptionsSchema` publishes
//!   ([`scanbus-dbus-api.md`] §6), and
//! - [`stored_defaults`] seeds a fresh profile store.
//!
//! The point is not the new property on its own; it is that the property cannot drift
//! from the validator. A format added to one and not the other would make
//! `OptionsSchema` a lie the day it landed, and §6 tells clients to trust it over the
//! prose.
//!
//! # What the table cannot hold
//!
//! [`Fallback::OutputFolder`] is the exception, and the reason the schema is generated by
//! the registry rather than being a constant: the effective default of `output_folder` is
//! a path this daemon computes from the XDG user directories, so the table can only say
//! *that it is computed*, not what it is. [`schema`] takes the resolved directory as an
//! argument, and the caller is the one place that knows it —
//! [`ProfileRegistry`](super::ProfileRegistry), which is also what the processors ask for
//! their output directory. One resolution, two readers.
//!
//! [`scanbus-dbus-api.md`]: https://github.com/jeanparpaillon/scanbus_service/blob/master/docs/scanbus-dbus-api.md

use std::collections::BTreeMap;
use std::path::Path;

use scanbus_core::{ProfileKind, Value};

/// Output encoding — `image` picks between three spellings, `document` only has one.
pub const FORMAT: &str = "format";
/// JPEG quality, `1..=100`.
pub const QUALITY: &str = "quality";
/// One PDF for the batch, or one PDF per page.
pub const MULTI_PAGE: &str = "multi_page";
/// Where the result is written; absent means "wherever the daemon resolves".
pub const OUTPUT_FOLDER: &str = "output_folder";

/// The profiles exported as `Profile1` objects, and the only ones with a table.
///
/// `email` and `ocr` are design targets in §6: they have no processor, so declaring
/// options for them would publish a contract nothing honours.
pub const REGISTERED: &[ProfileKind] = &[ProfileKind::Image, ProfileKind::Document];

/// One option a profile accepts.
pub struct OptionDecl {
    /// The key in `Options`, `ProfileOptions` and `OptionsSchema` alike.
    pub key: &'static str,
    /// What a value has to be to be accepted.
    pub value: ValueType,
    /// What the daemon uses when the key is absent.
    pub fallback: Fallback,
    /// One short untranslated English line, published as `description`.
    pub description: &'static str,
}

/// The accepted shape of one option's value.
///
/// The constraints live *inside* the variant rather than beside it, so a boolean with a
/// `min` or a closed set of integers is not expressible in the first place.
pub enum ValueType {
    /// A string, restricted to `values` when that list is non-empty.
    Str {
        /// Every accepted spelling, including aliases (§6): `jpg` is `jpeg`.
        values: &'static [&'static str],
    },
    /// An integer within inclusive bounds.
    Integer { min: u64, max: u64 },
    /// A boolean.
    Boolean,
    /// A string carrying a local filesystem path — a separate type only so a client can
    /// offer a folder chooser instead of a text entry.
    Path,
}

/// The value the daemon falls back to when an option is absent.
///
/// This is the *effective* default of §6, not what the profile store happens to hold: a
/// client that wrote `Options` without `quality` still gets 90-quality JPEGs, and the
/// schema has to say so.
pub enum Fallback {
    Str(&'static str),
    Integer(u64),
    Boolean(bool),
    /// Resolved by the daemon at read time — see the module documentation.
    OutputFolder,
}

/// One option, resolved: what a client reads off `OptionsSchema`.
///
/// Separate from [`OptionDecl`] because `default` is a [`Value`] here rather than a
/// `'static` literal — the computed `output_folder` has to fit in it.
pub struct SchemaEntry {
    pub key: &'static str,
    /// `"string"`, `"integer"`, `"boolean"` or `"path"` — the widget-level vocabulary of
    /// §6, not a D-Bus signature.
    pub type_name: &'static str,
    pub default: Value,
    /// Empty when any value of `type_name` is accepted.
    pub values: &'static [&'static str],
    pub min: Option<Value>,
    pub max: Option<Value>,
    pub description: &'static str,
}

const IMAGE: &[OptionDecl] = &[
    OptionDecl {
        key: FORMAT,
        value: ValueType::Str {
            values: &["jpeg", "jpg", "png"],
        },
        fallback: Fallback::Str("jpeg"),
        description: "Encoding of the written page files",
    },
    OptionDecl {
        key: QUALITY,
        value: ValueType::Integer { min: 1, max: 100 },
        fallback: Fallback::Integer(90),
        description: "JPEG quality; ignored when format is png",
    },
    OptionDecl {
        key: OUTPUT_FOLDER,
        value: ValueType::Path,
        fallback: Fallback::OutputFolder,
        description: "Directory the pages are written to",
    },
];

const DOCUMENT: &[OptionDecl] = &[
    OptionDecl {
        key: FORMAT,
        value: ValueType::Str { values: &["pdf"] },
        fallback: Fallback::Str("pdf"),
        description: "Output document format",
    },
    OptionDecl {
        key: MULTI_PAGE,
        value: ValueType::Boolean,
        fallback: Fallback::Boolean(true),
        description: "Assemble every page into one PDF instead of one PDF per page",
    },
    OptionDecl {
        key: OUTPUT_FOLDER,
        value: ValueType::Path,
        fallback: Fallback::OutputFolder,
        description: "Directory the document is written to",
    },
];

/// Every option `kind` accepts.
///
/// # Errors
///
/// The profiles with no processor, so that a write against one fails where it is made
/// rather than at the end of a scan that has already consumed the paper.
pub fn declarations(kind: ProfileKind) -> Result<&'static [OptionDecl], String> {
    match kind {
        ProfileKind::Image => Ok(IMAGE),
        ProfileKind::Document => Ok(DOCUMENT),
        ProfileKind::Email | ProfileKind::Ocr => {
            Err(format!("profile {} is not implemented", kind.as_str()))
        }
    }
}

/// Checks a whole `Options` map against the table.
///
/// # Errors
///
/// The first key that is not declared, or whose value the declaration refuses. The
/// message names the profile and the key, because the client that sent it is looking at
/// its own source and not at ours.
pub fn validate(kind: ProfileKind, options: &BTreeMap<String, Value>) -> Result<(), String> {
    let declared = declarations(kind)?;

    for (key, value) in options {
        let Some(decl) = declared.iter().find(|decl| decl.key == key) else {
            return Err(format!("unknown {} option {key:?}", kind.as_str()));
        };
        decl.check(kind, value)?;
    }

    Ok(())
}

impl OptionDecl {
    /// Checks one value against this declaration.
    ///
    /// # Errors
    ///
    /// A wrong type, a value outside a closed set, or an integer outside its bounds.
    pub fn check(&self, kind: ProfileKind, value: &Value) -> Result<(), String> {
        let profile = kind.as_str();
        let key = self.key;

        match &self.value {
            ValueType::Str { values } => {
                let Value::Str(text) = value else {
                    return Err(format!("{profile} option {key} must be a string"));
                };
                if !values.is_empty() && !values.contains(&text.as_str()) {
                    return Err(format!(
                        "{profile} option {key} must be one of {}, got {text:?}",
                        values.join("/")
                    ));
                }
            }
            ValueType::Path => {
                if !matches!(value, Value::Str(_)) {
                    return Err(format!("{profile} option {key} must be a string"));
                }
            }
            ValueType::Boolean => {
                if !matches!(value, Value::Bool(_)) {
                    return Err(format!("{profile} option {key} must be a boolean"));
                }
            }
            ValueType::Integer { min, max } => {
                let number = as_u64(value)
                    .ok_or_else(|| format!("{profile} option {key} must be an integer"))?;
                if !(*min..=*max).contains(&number) {
                    return Err(format!(
                        "{profile} option {key} must be in {min}..={max}, got {number}"
                    ));
                }
            }
        }

        Ok(())
    }

    fn type_name(&self) -> &'static str {
        match self.value {
            ValueType::Str { .. } => "string",
            ValueType::Integer { .. } => "integer",
            ValueType::Boolean => "boolean",
            ValueType::Path => "path",
        }
    }

    /// The literal fallback, or `None` for the one the daemon computes.
    fn literal_fallback(&self) -> Option<Value> {
        match self.fallback {
            Fallback::Str(text) => Some(Value::Str(text.to_owned())),
            Fallback::Integer(number) => Some(Value::U64(number)),
            Fallback::Boolean(flag) => Some(Value::Bool(flag)),
            Fallback::OutputFolder => None,
        }
    }
}

/// The whole table of `kind`, resolved into what `OptionsSchema` publishes.
///
/// `output_folder` is the directory this daemon would write to right now — §6's rule that
/// `default` is what the daemon *will use*, so that a client showing it for an unset
/// `output_folder` is not guessing.
///
/// An unimplemented profile answers with nothing rather than an error: it has no object,
/// so the only way to get here is a caller that already knows better.
pub fn schema(kind: ProfileKind, output_folder: &Path) -> Vec<SchemaEntry> {
    let Ok(declared) = declarations(kind) else {
        return Vec::new();
    };

    declared
        .iter()
        .map(|decl| {
            let (min, max) = match decl.value {
                ValueType::Integer { min, max } => (Some(Value::U64(min)), Some(Value::U64(max))),
                _ => (None, None),
            };

            SchemaEntry {
                key: decl.key,
                type_name: decl.type_name(),
                default: decl
                    .literal_fallback()
                    .unwrap_or_else(|| Value::Str(output_folder.to_string_lossy().to_string())),
                values: match decl.value {
                    ValueType::Str { values } => values,
                    _ => &[],
                },
                min,
                max,
                description: decl.description,
            }
        })
        .collect()
}

/// The options a fresh profile store holds for `kind`.
///
/// Only the literal fallbacks: `output_folder` is deliberately left unset, so that the
/// daemon keeps resolving it — writing today's resolved path into the store would freeze
/// it against a later change of `XDG_PICTURES_DIR`.
pub fn stored_defaults(kind: ProfileKind) -> BTreeMap<String, Value> {
    declarations(kind)
        .unwrap_or(&[])
        .iter()
        .filter_map(|decl| Some((decl.key.to_owned(), decl.literal_fallback()?)))
        .collect()
}

/// The string `key` carries, or its declared fallback.
///
/// Reading goes through the table too, so a processor cannot fall back to something the
/// schema does not publish. The value is checked on the way out because the options a
/// processor receives are the *merged* ones — a `Button1.ProfileOptions` override reaches
/// it without having passed [`validate`].
///
/// # Errors
///
/// Whatever [`OptionDecl::check`] refuses, or an undeclared `key` — which is a bug in
/// this crate rather than something a client can cause.
pub fn string_value<'a>(
    kind: ProfileKind,
    key: &str,
    options: &'a BTreeMap<String, Value>,
) -> Result<&'a str, String> {
    let decl = declaration(kind, key)?;

    match options.get(key) {
        Some(value) => {
            decl.check(kind, value)?;
            match value {
                Value::Str(text) => Ok(text.as_str()),
                // `check` already refused everything else for a `Str`/`Path` option.
                _ => Err(format!("{} option {key} must be a string", kind.as_str())),
            }
        }
        None => match decl.fallback {
            Fallback::Str(text) => Ok(text),
            _ => Err(format!(
                "{} option {key} has no string fallback",
                kind.as_str()
            )),
        },
    }
}

/// The integer `key` carries, or its declared fallback. See [`string_value`].
///
/// # Errors
///
/// As [`string_value`].
pub fn integer_value(
    kind: ProfileKind,
    key: &str,
    options: &BTreeMap<String, Value>,
) -> Result<u64, String> {
    let decl = declaration(kind, key)?;

    match options.get(key) {
        Some(value) => {
            decl.check(kind, value)?;
            as_u64(value)
                .ok_or_else(|| format!("{} option {key} must be an integer", kind.as_str()))
        }
        None => match decl.fallback {
            Fallback::Integer(number) => Ok(number),
            _ => Err(format!(
                "{} option {key} has no integer fallback",
                kind.as_str()
            )),
        },
    }
}

/// The boolean `key` carries, or its declared fallback. See [`string_value`].
///
/// # Errors
///
/// As [`string_value`].
pub fn boolean_value(
    kind: ProfileKind,
    key: &str,
    options: &BTreeMap<String, Value>,
) -> Result<bool, String> {
    let decl = declaration(kind, key)?;

    match options.get(key) {
        Some(value) => {
            decl.check(kind, value)?;
            match value {
                Value::Bool(flag) => Ok(*flag),
                _ => Err(format!("{} option {key} must be a boolean", kind.as_str())),
            }
        }
        None => match decl.fallback {
            Fallback::Boolean(flag) => Ok(flag),
            _ => Err(format!(
                "{} option {key} has no boolean fallback",
                kind.as_str()
            )),
        },
    }
}

fn declaration(kind: ProfileKind, key: &str) -> Result<&'static OptionDecl, String> {
    declarations(kind)?
        .iter()
        .find(|decl| decl.key == key)
        .ok_or_else(|| format!("unknown {} option {key:?}", kind.as_str()))
}

/// The integer an option carries, whichever way round a client signed it.
///
/// `convert::from_value` widens every D-Bus integer into one of two variants (2.5), so an
/// option written as `y`, `q` or `u` arrives here as [`Value::U64`] and one written as
/// `i` as [`Value::I64`]. Both mean the number the client typed.
pub fn as_u64(value: &Value) -> Option<u64> {
    match value {
        Value::U64(v) => Some(*v),
        Value::I64(v) if *v >= 0 => Some(*v as u64),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A path no resolution would ever produce, so a test that sees it knows where it
    /// came from.
    fn resolved() -> &'static Path {
        Path::new("/nowhere/scanbus/test")
    }

    /// The sync check 10.13 exists for: what the schema publishes and what the validator
    /// accepts are the same key set, in both directions.
    #[test]
    fn the_schema_and_the_validator_agree_on_the_key_set() {
        for &kind in REGISTERED {
            let published: Vec<&str> = schema(kind, resolved())
                .iter()
                .map(|entry| entry.key)
                .collect();
            assert!(
                !published.is_empty(),
                "{} publishes no options at all",
                kind.as_str()
            );

            // Every published key is one the validator recognises: it may refuse the
            // value, but never with "unknown option".
            for key in &published {
                let probe = BTreeMap::from([((*key).to_owned(), Value::Str(String::new()))]);
                if let Err(error) = validate(kind, &probe) {
                    assert!(
                        !error.contains("unknown"),
                        "{} publishes {key}, which the validator does not know: {error}",
                        kind.as_str()
                    );
                }
            }

            // And the other way: a key the table does not declare is refused, so the
            // published set is the whole accepted set rather than a subset of it.
            let undeclared = BTreeMap::from([(
                "an_option_nobody_declared".to_owned(),
                Value::Str(String::new()),
            )]);
            let error = validate(kind, &undeclared).expect_err("an undeclared key is refused");
            assert!(error.contains("unknown"), "{error}");
        }
    }

    /// Every declared default is a value the same declaration accepts — the check that
    /// catches a table edited on one line only.
    #[test]
    fn every_default_satisfies_its_own_declaration() {
        for &kind in REGISTERED {
            for entry in schema(kind, resolved()) {
                let decl = declaration(kind, entry.key).unwrap();
                decl.check(kind, &entry.default).unwrap_or_else(|error| {
                    panic!(
                        "{}'s default for {} is not a value it accepts: {error}",
                        kind.as_str(),
                        entry.key
                    )
                });

                assert!(
                    !entry.description.is_empty(),
                    "{}.{} has no description",
                    kind.as_str(),
                    entry.key
                );
            }
        }
    }

    /// §6's shape rules, on the entries this daemon actually publishes: a closed set
    /// contains its own default, and bounds bracket it.
    #[test]
    fn constraints_bracket_the_defaults_they_constrain() {
        for &kind in REGISTERED {
            for entry in schema(kind, resolved()) {
                if !entry.values.is_empty() {
                    let Value::Str(default) = &entry.default else {
                        panic!(
                            "{}.{} has values but no string default",
                            kind.as_str(),
                            entry.key
                        );
                    };
                    assert!(
                        entry.values.contains(&default.as_str()),
                        "{}.{} defaults to {default:?}, which is not one of {:?}",
                        kind.as_str(),
                        entry.key,
                        entry.values
                    );
                }

                match (&entry.min, &entry.max) {
                    (Some(Value::U64(min)), Some(Value::U64(max))) => {
                        let default = as_u64(&entry.default).expect("a bounded option is numeric");
                        assert!(min <= &default && &default <= max);
                    }
                    (None, None) => {}
                    _ => panic!("{}.{} has only one bound", kind.as_str(), entry.key),
                }
            }
        }
    }

    /// The computed default is the caller's path, and it is the only computed one — if a
    /// second option ever becomes computed this test is where that is noticed.
    #[test]
    fn output_folder_is_the_one_default_the_table_does_not_hold() {
        for &kind in REGISTERED {
            let entries = schema(kind, resolved());
            let computed: Vec<&str> = entries
                .iter()
                .filter(|entry| {
                    declaration(kind, entry.key)
                        .map(|decl| matches!(decl.fallback, Fallback::OutputFolder))
                        .unwrap_or(false)
                })
                .map(|entry| entry.key)
                .collect();
            assert_eq!(computed, [OUTPUT_FOLDER]);

            let folder = entries
                .iter()
                .find(|entry| entry.key == OUTPUT_FOLDER)
                .unwrap();
            assert_eq!(folder.type_name, "path");
            assert_eq!(
                folder.default,
                Value::Str(resolved().to_string_lossy().to_string())
            );
        }
    }

    /// The store is seeded from the table, minus what the daemon resolves for itself.
    #[test]
    fn stored_defaults_leave_the_computed_option_unset() {
        let image = stored_defaults(ProfileKind::Image);
        assert_eq!(image.get(FORMAT), Some(&Value::Str("jpeg".to_owned())));
        assert_eq!(image.get(QUALITY), Some(&Value::U64(90)));
        assert!(
            !image.contains_key(OUTPUT_FOLDER),
            "a stored output_folder would freeze the resolved path"
        );

        // And what it seeds is accepted by the validator, which is what makes a fresh
        // store loadable at all.
        validate(ProfileKind::Image, &image).unwrap();
        validate(
            ProfileKind::Document,
            &stored_defaults(ProfileKind::Document),
        )
        .unwrap();
    }

    /// The refusals, in the words a client reads.
    #[test]
    fn a_value_outside_its_declaration_is_named_in_the_refusal() {
        let error = validate(
            ProfileKind::Image,
            &BTreeMap::from([(FORMAT.to_owned(), Value::Str("tiff".to_owned()))]),
        )
        .expect_err("tiff is not a declared format");
        assert!(error.contains("jpeg/jpg/png"), "{error}");

        let error = validate(
            ProfileKind::Image,
            &BTreeMap::from([(QUALITY.to_owned(), Value::U64(200))]),
        )
        .expect_err("200 is out of bounds");
        assert!(error.contains("1..=100"), "{error}");

        let error = validate(
            ProfileKind::Document,
            &BTreeMap::from([(MULTI_PAGE.to_owned(), Value::Str("yes".to_owned()))]),
        )
        .expect_err("multi_page is a boolean");
        assert!(error.contains("boolean"), "{error}");

        let error = validate(ProfileKind::Ocr, &BTreeMap::new())
            .expect_err("ocr has no processor and so no options");
        assert!(error.contains("not implemented"), "{error}");
    }

    /// A client that sent `quality` as a signed integer means the same number.
    #[test]
    fn integers_are_read_whichever_way_round_they_were_signed() {
        let options = BTreeMap::from([(QUALITY.to_owned(), Value::I64(40))]);
        assert_eq!(
            integer_value(ProfileKind::Image, QUALITY, &options).unwrap(),
            40
        );
        assert_eq!(
            integer_value(ProfileKind::Image, QUALITY, &BTreeMap::new()).unwrap(),
            90,
            "an absent option reads as the declared fallback"
        );
    }
}
