[package]
name = "scanbus-backend-mobile"
description = "Mobile protocol backend for scanbus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
scanbus-backend-common = { workspace = true, features = ["mdns"] }
scanbus-core.workspace = true
async-trait.workspace = true
futures-core.workspace = true
futures-util.workspace = true
if-addrs.workspace = true
mdns-sd.workspace = true
rand.workspace = true
rcgen.workspace = true
rustls.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util", "net", "time"] }
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
